/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_edgeconfig_free: (a: number, b: number) => void;
export const __wbg_edgehost_free: (a: number, b: number) => void;
export const __wbg_edgereply_free: (a: number, b: number) => void;
export const edgeconfig_new: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number) => number;
export const edgehost_fetch: (a: number, b: number, c: number, d: number) => number;
export const edgereply_continuation: (a: number) => number;
export const edgereply_takeResponse: (a: number) => number;
export const start: (a: number) => number;
export const __wbg_intounderlyingbytesource_free: (a: number, b: number) => void;
export const __wbg_intounderlyingsink_free: (a: number, b: number) => void;
export const __wbg_intounderlyingsource_free: (a: number, b: number) => void;
export const intounderlyingbytesource_autoAllocateChunkSize: (a: number) => number;
export const intounderlyingbytesource_cancel: (a: number) => void;
export const intounderlyingbytesource_pull: (a: number, b: number) => number;
export const intounderlyingbytesource_start: (a: number, b: number) => void;
export const intounderlyingbytesource_type: (a: number) => number;
export const intounderlyingsink_abort: (a: number, b: number) => number;
export const intounderlyingsink_close: (a: number) => number;
export const intounderlyingsink_write: (a: number, b: number) => number;
export const intounderlyingsource_cancel: (a: number) => void;
export const intounderlyingsource_pull: (a: number, b: number) => number;
export const __wasm_bindgen_func_elem_59464: (a: number, b: number, c: number, d: number) => void;
export const __wasm_bindgen_func_elem_59466: (a: number, b: number, c: number, d: number) => void;
export const __wasm_bindgen_func_elem_1902: (a: number, b: number, c: number) => number;
export const __wasm_bindgen_func_elem_1902_3: (a: number, b: number, c: number) => number;
export const __wasm_bindgen_func_elem_8758: (a: number, b: number, c: number) => void;
export const __wasm_bindgen_func_elem_8499: (a: number, b: number) => void;
export const __wbindgen_export: (a: number, b: number) => number;
export const __wbindgen_export2: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_export3: (a: number) => void;
export const __wbindgen_export4: (a: number, b: number, c: number) => void;
export const __wbindgen_export5: (a: number, b: number) => void;
export const __wbindgen_add_to_stack_pointer: (a: number) => number;
